# Generated by Django 2.2.4 on 2019-08-23 04:13

from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=6)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('takeoff_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('gate', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('seats', models.PositiveIntegerField(default=0, validators=[flights.models.validate_seats])),
                ('status', models.CharField(default='active', max_length=10, validators=[flights.models.validate_status])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
