# Generated by Django 2.2.4 on 2019-08-23 22:46

from django.db import migrations, models
import django.db.models.deletion
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('code', models.CharField(max_length=3, validators=[flights.models.validate_airport_code])),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinations', to='flights.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flights', to='flights.Airport'),
        ),
    ]
