# Generated by Django 2.2.4 on 2019-08-24 00:33

from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20190823_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[flights.models.validate_airport_code]),
        ),
    ]
