# Generated by Django 2.2.4 on 2019-08-24 20:11

from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20190824_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.IntegerField(validators=[flights.models.validate_seats]),
        ),
    ]
