# Generated by Django 2.2.4 on 2019-08-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image_url'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
