# Generated by Django 2.2.4 on 2019-08-27 03:50

import cloudinary.models
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190826_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/health-id/image/upload/v1554552278/Profile_Picture_Placeholder.png', max_length=255, validators=[user.models.validate_image], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[user.models.validate_pwd]),
        ),
    ]
