# Generated by Django 2.2.4 on 2019-08-23 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('payment_status', models.CharField(default='reserved', max_length=8, validators=[tickets.models.validate_payment_status])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='flights.Flight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
